/**
 * Supervisor manager.
 *
 * Programs are written to `<dir>/laravel-<slug>-worker.conf` and are always
 * tagged with our marker so we never read, rewrite or restart a program we did
 * not create (SPEC §25).
 */

import { assertProgramName, q } from '../../utils/shell.js';
import { RemoteCommandError } from '../../core/errors/errors.js';
import { SUPERVISOR_MARKER, parseSupervisorStatus, type WorkerPlan } from '../../laravel/workers.js';
import type { RemoteExecutor } from '../exec/types.js';

export interface SupervisorManagerOptions {
  executor: RemoteExecutor;
  /** aaPanel keeps programs in /etc/supervisor/conf.d. */
  configDir?: string;
  /** aaPanel prefixes programs with the program name itself. */
  programPrefix?: string;
  /** Binary name; `supervisorctl` or aaPanel's `supervisorctl`. */
  ctl?: string;
  /** Command used to reload the supervisor daemon. */
  reread?: string;
  update?: string;
}

export interface SupervisorInstallResult {
  written: string[];
  updated: string[];
  unchanged: string[];
  reread: boolean;
  restart: boolean;
}

/**
 * Where supervisorctl may live, most specific first. aaPanel installs its own
 * copy inside its bundled Python and does not expose it on the SSH user's PATH.
 */
const SUPERVISORCTL_CANDIDATES = [
  'supervisorctl',
  '/www/server/panel/pyenv/bin/supervisorctl',
  '/usr/local/bin/supervisorctl',
  '/usr/bin/supervisorctl',
] as const;

export class SupervisorManager {
  private readonly configDir: string;
  private readonly ctl: string;
  private resolvedCtl: string | null = null;

  constructor(private readonly options: SupervisorManagerOptions) {
    this.configDir = options.configDir ?? '/etc/supervisor/conf.d';
    this.ctl = options.ctl ?? 'supervisorctl';
  }

  /**
   * The supervisorctl to invoke.
   *
   * aaPanel does not put supervisorctl on an SSH user's PATH — it ships one
   * inside its bundled Python at /www/server/panel/pyenv/bin — so calling the
   * bare name fails with "command not found" even on a server where supervisor
   * is installed and running. Resolve it once and cache the answer.
   */
  private async ctlPath(): Promise<string> {
    if (this.options.ctl) return this.ctl;
    if (this.resolvedCtl) return this.resolvedCtl;
    const result = await this.run(
      `for candidate in ${SUPERVISORCTL_CANDIDATES.map((c) => q(c)).join(' ')}; do
  if command -v "$candidate" >/dev/null 2>&1; then command -v "$candidate"; exit 0; fi
  if [ -x "$candidate" ]; then echo "$candidate"; exit 0; fi
done
exit 1`,
      { allowFailure: true, label: 'locate supervisorctl' },
    );
    const found = result.exitCode === 0 ? result.stdout.trim().split('\n').pop()?.trim() : '';
    if (!found) return this.ctl; // Keep the bare name so the error names it.
    this.resolvedCtl = found;
    return found;
  }

  /** Path of the program definition for a given name. */
  programFile(name: string): string {
    // Validated because this becomes a path under /etc/supervisor/conf.d, and
    // `remove()` passes it to `rm -f`.
    return `${this.configDir}/${assertProgramName(name)}.conf`;
  }

  /**
   * Quote a list of program names for a supervisorctl invocation.
   *
   * Names are validated *and* quoted: the validation keeps them from carrying
   * shell metacharacters at all, and the quoting means a future caller that
   * skips validation still cannot break out of the command.
   */
  private ctlArgs(names: readonly string[]): string {
    return names.map((name) => assertProgramName(name)).map((name) => q(name)).join(' ');
  }

  /**
   * Render a program definition. `directory` must be `current/` so the worker
   * picks up the new release on restart.
   */
  renderProgram(input: {
    plan: WorkerPlan;
    siteRoot: string;
    phpBinary: string;
    envFile?: string;
  }): string {
    const queue = input.plan.connection ?? 'default';
    const args = ['artisan', 'queue:work', `--queue=${queue}`, ...input.plan.options];
    const environment = input.envFile ? `,environment=APP_ENV="production",SHELL="/bin/bash"` : '';
    return [
      SUPERVISOR_MARKER,
      '; Regenerated by `laravel-deploy queue install`. Edits will be overwritten.',
      `[program:${input.plan.programName}]`,
      'command=' + [input.phpBinary, ...args].map((part) => (/[\s"']/.test(part) ? `"${part.replace(/"/g, '\\"')}"` : part)).join(' '),
      `directory=${input.siteRoot}/current`,
      'autostart=true',
      'autorestart=true',
      'stopasgroup=true',
      'killasgroup=true',
      'numprocs=1',
      'user=root',
      'redirect_stderr=true',
      `stdout_logfile=${input.siteRoot}/shared/logs/queue-${input.plan.programName}.log`,
      `stdout_logfile_maxbytes=10MB`,
      'stopwaitsecs=10',
      environment,
      '',
    ].join('\n');
  }

  /**
   * Install or update programs without duplicating them.
   * Comparison is content-based, so an unchanged program is not restarted.
   */
  async install(
    plans: readonly WorkerPlan[],
    input: { siteRoot: string; phpBinary: string; restart?: boolean },
  ): Promise<SupervisorInstallResult> {
    const written: string[] = [];
    const updated: string[] = [];
    const unchanged: string[] = [];
    const restartNeeded: string[] = [];

    for (const plan of plans) {
      const file = this.programFile(plan.programName);
      const contents = this.renderProgram({
        plan,
        siteRoot: input.siteRoot,
        phpBinary: input.phpBinary,
      });

      const exists = await this.fileExists(file);
      if (!exists) {
        await this.writeFile(file, contents);
        written.push(plan.programName);
        restartNeeded.push(plan.programName);
        continue;
      }
      const current = await this.readFile(file);
      if (current === contents) {
        unchanged.push(plan.programName);
        continue;
      }
      await this.writeFile(file, contents);
      updated.push(plan.programName);
      restartNeeded.push(plan.programName);
    }

    // Pick up new/changed definitions without touching other programs.
    const ctl = await this.ctlPath();
    await this.run(`${ctl} reread`, { allowFailure: true, label: 'supervisor reread' });
    await this.run(
      `cd ${q('/etc/supervisor*')} 2>/dev/null || true; ${ctl} update`,
      { allowFailure: true, label: 'supervisor update' },
    );

    let restart = false;
    if ((input.restart ?? true) && restartNeeded.length > 0) {
      restart = await this.restart(restartNeeded);
    }

    return { written, updated, unchanged, reread: true, restart };
  }

  /**
   * Restart only the named programs.
   *
   * `waitSeconds` is what makes `queue.restartTimeoutSeconds` mean something.
   * `supervisorctl restart` exits 0 the moment it has asked the daemon to stop
   * and start a program; a worker that dies on boot — bad credentials, a
   * missing extension, a migration lock — still comes back "successfully" and
   * the deploy walks away with a silently dead queue. Polling until every named
   * program is RUNNING is the difference between restarting workers and
   * checking that they came back.
   */
  async restart(names: readonly string[], options: { waitSeconds?: number } = {}): Promise<boolean> {
    if (names.length === 0) return false;
    const result = await this.run(`${await this.ctlPath()} restart ${this.ctlArgs(names)}`, {
      label: 'supervisor restart',
    });
    if (result.exitCode !== 0) return false;

    const waitSeconds = options.waitSeconds ?? 0;
    if (waitSeconds <= 0) return true;

    const deadline = Date.now() + waitSeconds * 1000;
    // Poll fast enough that a 15s budget is not spent sleeping, slow enough
    // that we are not asking supervisorctl for status 40 times a second.
    const intervalMs = Math.min(2_000, Math.max(250, Math.round((waitSeconds * 1000) / 10)));
    for (;;) {
      const states = await this.status();
      if (names.every((name) => states.some((s) => s.name === name && s.state === 'RUNNING'))) {
        return true;
      }
      const remaining = deadline - Date.now();
      if (remaining <= 0) return false;
      await sleep(Math.min(intervalMs, remaining));
    }
  }

  /** Stop only the named programs. */
  async stop(names: readonly string[]): Promise<boolean> {
    if (names.length === 0) return false;
    const result = await this.run(`${await this.ctlPath()} stop ${this.ctlArgs(names)}`, {
      allowFailure: true,
    });
    return result.exitCode === 0;
  }

  /** All supervisor processes, filtered to ours. */
  async status(): Promise<ReturnType<typeof parseSupervisorStatus>> {
    const result = await this.run(`${await this.ctlPath()} status`, { allowFailure: true });
    if (result.exitCode !== 0) return [];
    const parsed = parseSupervisorStatus(result.stdout);
    return parsed.filter((row) => row.name.startsWith('laravel-'));
  }

  /** Remove our program definitions. Only ever touches files we wrote. */
  async remove(names: readonly string[]): Promise<string[]> {
    const removed: string[] = [];
    for (const name of names) {
      const file = this.programFile(name);
      const contents = await this.readFile(file);
      if (contents === null) continue;
      // Refuse to delete a definition we did not write.
      if (!contents.includes(SUPERVISOR_MARKER)) {
        throw new RemoteCommandError(
          `Refusing to remove ${file}: it is not managed by laravel-deploy.`,
          1,
          { command: `rm ${file}` },
        );
      }
      await this.stop([name]);
      await this.run(`rm -f ${q(file)}`, { label: 'remove supervisor program' });
      const ctl = await this.ctlPath();
      await this.run(`${ctl} reread`, { allowFailure: true });
      await this.run(`${ctl} update`, { allowFailure: true });
      removed.push(name);
    }
    return removed;
  }

  /** Tail a worker's log. */
  async logs(name: string, lines: number, follow: boolean): Promise<void> {
    const path = `/var/log/supervisor/${name}.log`;
    const command = follow
      ? `tail -n ${lines} -f ${q(path)}`
      : `tail -n ${lines} ${q(path)} 2>/dev/null || journalctl -u ${q(`supervisor-${name}`)} -n ${lines} --no-pager`;
    const result = await this.run(command, { allowFailure: true, timeoutMs: follow ? -1 : 30_000 });
    process.stdout.write(result.stdout);
    if (result.stderr) process.stderr.write(result.stderr);
  }

  /** True when supervisorctl exists. */
  async available(): Promise<boolean> {
    const resolved = await this.ctlPath();
    const result = await this.run(`test -x ${q(resolved)} || command -v ${q(resolved)}`, {
      allowFailure: true,
    });
    return result.exitCode === 0;
  }

  private async fileExists(path: string): Promise<boolean> {
    const result = await this.options.executor.exec(`test -f ${q(path)}`, { allowFailure: true });
    return result.exitCode === 0;
  }

  private async readFile(path: string): Promise<string | null> {
    const result = await this.options.executor.exec(`cat ${q(path)} 2>/dev/null`, {
      allowFailure: true,
    });
    return result.exitCode === 0 ? result.stdout : null;
  }

  private async writeFile(path: string, contents: string): Promise<void> {
    const tag = `LDSUP${Math.random().toString(36).slice(2, 10).toUpperCase()}`;
    const script = [
      'set -Eeuo pipefail',
      `mkdir -p ${q(this.configDir)}`,
      `cat > ${q(path)} <<'${tag}'`,
      contents.replace(/\n?$/, ''),
      `${tag}`,
      `chmod 0644 ${q(path)}`,
    ].join('\n');
    const result = await this.run(script, { label: 'write supervisor program', allowFailure: true });
    if (result.exitCode !== 0) {
      throw new RemoteCommandError(`Unable to write ${path}.`, result.exitCode, {
        details: { stderr: result.stderr.slice(-2000) },
        remediation: ['Check that the SSH user can write to the supervisor config directory.'],
      });
    }
  }

  private run(
    command: string,
    options: { allowFailure?: boolean; label?: string; timeoutMs?: number },
  ) {
    return this.options.executor.exec(command, {
      allowFailure: options.allowFailure ?? false,
      label: options.label,
      timeoutMs: options.timeoutMs,
    });
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}