/**
 * Site layout.
 *
 * Two shapes, chosen by `site.documentRootStrategy`:
 *
 * Modern (default):
 *   <root>/current  -> releases/<id>          (atomic symlink)
 *   <root>/releases/<id>/{app,public,...}
 *   <root>/shared/{.env,storage}
 *   web root: <root>/current/public
 *
 * Legacy (aaPanel style, opt-in):
 *   <root>/main/{app,public,...}
 *   <root>/index.php                          (rewritten)
 *   public assets copied to <root>/
 *   web root: <root>
 */

import { assertRemotePath } from '../../utils/shell.js';
import type { DocumentRootStrategy } from '../config/schema.js';

export interface SiteLayout {
  root: string;
  strategy: DocumentRootStrategy;
  /** Directory holding the live application code for this strategy. */
  appDir: string;
  /** Directory the web server serves. */
  documentRoot: string;
  releasesDir: string;
  sharedDir: string;
  currentLink: string;
  envPath: string;
  sharedStorageDir: string;
  /** Alias used by the command layer. */
  readonly sharedStorage: string;
  sharedLogsDir: string;
  incomingDir: string;
  deployDir: string;
  backupsDir: string;
  lockFile: string;
  manifestPath: string;
  /** Public asset destination for legacy mode. */
  legacyPublicTarget?: string;
}

export function buildLayout(input: {
  root: string;
  strategy: DocumentRootStrategy;
  /** Subdirectory holding the app in legacy mode. */
  legacyMainDir?: string;
  /** Subdirectory deploy backups are written to. */
  backupDirName?: string;
}): SiteLayout & { sharedStorage: string } {
  const root = assertRemotePath(input.root.replace(/\/+$/, ''), 'site root');
  const legacy = input.strategy === 'legacy-root-copy';
  const mainDir = input.legacyMainDir ?? 'main';
  const backupsDirName = input.backupDirName ?? 'deploy-backups';

  return {
    root,
    strategy: input.strategy,
    // Legacy mode has no releases/ symlink; the app lives in `main`.
    appDir: legacy ? `${root}/${mainDir}` : `${root}/current`,
    documentRoot: legacy ? root : `${root}/current/public`,
    releasesDir: `${root}/releases`,
    sharedDir: `${root}/shared`,
    currentLink: `${root}/current`,
    // The .env lives in shared/ in both modes so it survives every deploy.
    envPath: `${root}/shared/.env`,
    sharedStorageDir: `${root}/shared/storage`,
    sharedLogsDir: `${root}/shared/logs`,
    incomingDir: `${root}/.deploy/incoming`,
    deployDir: `${root}/.deploy`,
    backupsDir: `${root}/${backupsDirName}`,
    lockFile: `${root}/.deploy/deployment.lock`,
    manifestPath: `${root}/deployment-manifest.json`,
    sharedStorage: `${root}/shared/storage`,
    ...(legacy ? { legacyPublicTarget: root } : {}),
  };
}

/** Path of one release inside the releases directory. */
export function releasePath(layout: SiteLayout, releaseId: string): string {
  return `${layout.releasesDir}/${releaseId}`;
}

/** Incoming archive path for a release. */
export function incomingArchivePath(layout: SiteLayout, releaseId: string, format: 'tar.gz' | 'zip' = 'tar.gz'): string {
  return `${layout.incomingDir}/${releaseId}.${format}`;
}

/** Where a script is staged on the server. */
export function scriptPath(layout: SiteLayout, name: string): string {
  return `${layout.deployDir}/scripts/${name}`;
}

/** Directories that must exist for a release to work. */
export function releaseDirectories(layout: SiteLayout): string[] {
  if (layout.strategy === 'legacy-root-copy') {
    return [layout.appDir, layout.sharedDir, layout.sharedStorageDir, layout.sharedLogsDir];
  }
  return [layout.releasesDir, layout.sharedDir, layout.sharedStorageDir, layout.sharedLogsDir];
}

/** Build the legacy `index.php` that points into `main/`. */
export function legacyIndexPhp(input: {
  mainDir: string;
  /** Path relative to the site root where index.php lives. */
  prefix?: string;
}): string {
  const prefix = (input.prefix ?? '').replace(/^\/+|\/+$/g, '');
  const base = prefix === '' ? input.mainDir : `${prefix}/${input.mainDir}`;
  return `<?php

/*
 * Generated by laravel-deploy (documentRootStrategy=legacy-root-copy).
 * Do not edit by hand — this file is rewritten on every deployment.
 */

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
*/

require ${base}/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
*/

$app = require_once ${base}/bootstrap/app.php;

/*
|--------------------------------------------------------------------------
| Handle The Request
|--------------------------------------------------------------------------
*/

$app->handleRequest(Request::capture());
`;
}

/** Directories the legacy strategy copies out of public/. */
export const LEGACY_PUBLIC_ENTRIES = ['assets', 'build', 'css', 'js', 'images', 'img', 'fonts', 'favicon.ico', 'robots.txt'] as const;

/**
 * Site-root entries the legacy public copy must never clobber (SPEC §64).
 *
 * `.user.ini` and `.well-known` belong to aaPanel and Let's Encrypt;
 * `.htaccess` belongs to the panel's Apache setups and carries the rewrite
 * rules the vhost depends on; `index.php` is the bootstrap laravel-deploy
 * generates, and Laravel's own `public/index.php` must not be copied over it.
 *
 * Entries must be plain names. `prepare-release.sh` re-checks this, because the
 * list comes from a config file that is treated as untrusted input.
 */
export function legacyPreservedEntries(configured: readonly string[]): string[] {
  return [
    ...new Set([
      '.user.ini',
      '.htaccess',
      '.well-known',
      'index.php',
      ...configured.filter((entry) => /^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(entry)),
    ]),
  ];
}